### ISSUE TITLE
Using XState

### ISSUE THREAD

**Issue by geddski** [lukeed/vegemite#3]
Hey there @lukeed. Way cool lib! I'm playing around with it (in React) and for some reason as soon as I dispatch an event I get this error:

```
Kolo.tsx:24 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Object.toString (<anonymous>)
    at klona (klona.js:4)
    at klona (klona.js:17)
    at klona (klona.js:17)
    at klona (klona.js:17)
    at klona (klona.js:17)
    at klona (klona.js:17)
    at klona (klona.js:17)
    at klona (klona.js:17)
    at klona (klona.js:17)
```

Any ideas?

**Comment by lukeed** [comment]
Hey, thanks~!

What are you passing in as state? And what kind of data are you dispatching to your event?

**Comment by geddski** [comment]
hmm when I simplified my example the error went away. I was storing XState state machines & services in the vegemite store. Maybe those complex objects gave it trouble?

**Comment by geddski** [comment]
yep adding the state machine back to the store causes it

```js
const store = vegemite<EventMap, State>({
      // breaks w a complex object (state machine)
      kolo: {
        machine: koloMachine
        // service: koloService
      }
      // works with a simple object
      // kolo: {
      //   isAwesome: false
      // }
    });
```

**Comment by lukeed** [comment]
I think that means XState objects are circular.

How do I create `koloMachine`?

**Comment by lukeed** [comment]
FWIW, I don't know if I would nest a state machine _inside_ of a Vegemite store. In principle you could, but it makes more sense to have them be siblings, with Vegemite acting as an app-wide event bus that feeds values into XState since that's (presumably) where all your derived/computed/business logic is living

**Comment by geddski** [comment]
> I think that means XState objects are circular

yep looks likely.

> have them be siblings

good idea I'll try that. Thx!

**Comment by lukeed** [comment]
I assume this means everything worked out? 😅

**Comment by geddski** [comment]
still in progress but now I know it's not a Vegemite bug!

**Comment by lukeed** [comment]
Haha okay, good luck!
