### ISSUE TITLE
React support?

### ISSUE THREAD

**Issue by danawoodman** [lukeed/vegemite#4]
Cool project! I like how simple the API is and the pub/sub model. 

Do you have plans to support a React integration?

**Comment by lukeed** [comment]
Thanks, it does! There are two examples with Preact in the repo -- one of them utilises typescript too 👍

**Comment by danawoodman** [comment]
Ah sorry, maybe it would be good to mention these examples in the README for new users who don't think to look in the examples folder like me 😄

**Comment by danawoodman** [comment]
And also, i think there are a lot of devs out there that don't realize Preact is an API-compatible React, so maybe a CRA example would be valuable for adoption?
