### ISSUE TITLE
Is using complex types like Map and Set with Vegemite ok?

### ISSUE THREAD

**Issue by matthewharwood** [lukeed/vegemite#7]
Hey I like complex browser types like Map and Sets it seemingly works in Vegemite but would you suggest not to use them?

```
import vegemite from "vegemite";
let store = vegemite({ entry: new Map() });

let detach = store.on("entry:add", (state, event) => {
  state.entry.set(...event);
});

async function main() {
  await store.dispatch("entry:add", ["hello", "world"]);
  console.log(store.state);
}

main().then(() => console.log("done"));

```

**Comment by lukeed** [comment]
Hey, 

Sure – they work just fine! It's a _little_ more expensive to clone them from state-to-state, but they'll be cloned correctly. 

I personally prefer simpler data-types whenever possible, but I have Sets & Maps in the wild too and there's no issue 👍
